name: Deploy to GitHub Pages
permissions:
  pages: write
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Git configuration
        run: git config --list --show-origin

      - name: Install dependencies
        run: npm install

      - name: Install and Build  # This example project is built using npm and outputs the result to the 'dist' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
          clean-exclude: |
            special-file.txt
            some/*.txt
          clean: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and deploy
      #   run: |
      #     npm run build
      #     git config --global user.name "github-actions"
      #     git config --global user.email "github-actions@github.com"
      #     git remote add origin https://github.com/${GITHUB_REPO}.git
      #     git push --quiet --force origin main:gh-pages